feat: signal handler
exciting-kfs/kfs pull request #123
Opened 2023-07-26 03:46 UTC by 42mypark

- feat: do_signal

- fix: named lock

- feat: sigaction

2023-07-26 04:10 UTC, 42-cjeon commented on src/process/task.rs
> +}
```suggestion
```

2023-07-26 04:15 UTC, 42-cjeon commented on src/signal/context.rs
> +		unsafe { copy_nonoverlapping(intr_frame, &mut intr as *mut InterruptFrame, 1) }
역참조?

2023-07-26 04:25 UTC, 42-cjeon commented on src/sync/locked.rs
> +impl<T: Clone> Clone for Locked<T> {
락이 필요할지도...?

2023-07-26 04:33 UTC, 42-cjeon commented on userspace/include/kfs/kernel.h
> +};
러스트쪽이랑 필드가 다르네요

2023-07-26 04:34 UTC, 42-cjeon commented on src/signal/handler.rs
> +}
#[repr(C)]

2023-07-26 04:44 UTC, 42-cjeon commented on src/signal.rs
> +	fn get_sig_info(&self) -> Option<SigInfo> {
sig_mask 락, 리팩토링?

2023-07-26 05:04 UTC, 42-cjeon commented on src/signal.rs
> +			sig_queue: self.sig_queue.clone(),
List::new()?

2023-07-26 05:07 UTC, 42-cjeon requested changes
코멘트 드린것만 수정하시면 될 것 같아요

2023-07-29 06:24 UTC, 42mypark commented on src/interrupt/syscall.rs
> +			});
if 문

2023-07-29 06:42 UTC, 42mypark commented on src/signal.rs
> +			o_mask - info.num.into() | act.mask()
-를 마지막에 해야함

2023-07-29 07:17 UTC, 42-cjeon approved these changes

2023-07-29 07:23 UTC, merged