Util for ext2(cast_box, lock_rw)
exciting-kfs/kfs pull request #172
Opened 2023-08-28 06:29 UTC by 42mypark

* feat: cast_box
* feat: lock_rw

2023-08-28 08:13 UTC, 42-cjeon commented on src/ptr/cast_box.rs
> +	pub unsafe fn into_box<T>(mut self) -> Box<T> {
`Box::from_raw()`를 쓰면 더 깔끔할 것 같아요

그리고 self와 box에서 소멸자가 2번 불리는 문제가 생길 것 같아요

2023-08-28 08:22 UTC, 42-cjeon commented on src/ptr/cast_box.rs
> +		chunks.into_iter().map(|chunk| CastChunk { chunk })
```suggestion
unsafe { self.ptr.as_mut() }.chunks_exact_mut(size).map(|chunk| CastChunk { chunk })
```

2023-08-28 08:32 UTC, 42-cjeon commented on src/sync/lock_rw.rs
> +		self.write_lock.lock();
T1(reader): self.write_lock.lock()
T1:(reader) self.write_lock.unlock()
T2(writer): self.write_lock()
T2(reader): self.read_count.fetch_add ...

상황에서 read_count가 올라가지 않은 상태에서 write lock을 획득해서 결과적으로 mutable / immutable 레퍼런스가 동시에 생길 수 있을 것 같아요.

추가적으로 Ordering도 Relaxed보다 조금 더 강한 제약이 걸려야 할 것 같아요.

2023-08-28 08:34 UTC, 42-cjeon commented on src/sync/lock_rw.rs
> +		self.lock.read_count.fetch_sub(1, Ordering::Relaxed);
relaxed?

2023-08-28 08:35 UTC, 42-cjeon requested changes
무시무시한 unsafe와 cast의 세계...

2023-08-28 08:37 UTC, 42mypark commented on src/ptr/cast_box.rs
> +	pub unsafe fn into_box<T>(mut self) -> Box<T> {
이게 from raw로 하지 않은 이유가 있는데요, Box에서 할당 해제할 때 타입의 레이아웃 가져와서 하는데, CastBox의 레이아웃과 서로 달라서, from raw로 해서 Box를 생성하면 해제가 제대로 안될 거 같아요.

2023-08-28 08:50 UTC, 42mypark commented on src/sync/lock_rw.rs
> +		self.write_lock.lock();
Add를 락 안으로 넣긴해야겠네요.

2023-08-28 08:59 UTC, 42mypark commented on src/sync/lock_rw.rs
> +		self.lock.read_count.fetch_sub(1, Ordering::Relaxed);
제 생각엔 여기는 문제 없을 거 같은데, write lock에서 이 값 확인하는 부분이 안전할지 고민이 되네요..

2023-08-29 02:38 UTC, 42-cjeon approved these changes
LGTM

2023-08-29 04:13 UTC, merged